CREATE SCHEMA AIRLINE;

USE AIRLINE;

CREATE TABLE AIRPORT(
AIRPORT_CODE VARCHAR(100),
NAME VARCHAR(200),
CITY VARCHAR(100),
STATE VARCHAR(100) ,
CONSTRAINT AIRPORT_PK 
PRIMARY KEY (AIRPORT_CODE) 
)



CREATE TABLE FLIGHT(
FLIGHT_NUMBER VARCHAR(300) ,
AIRLINE VARCHAR(300) NOT NULL,
WEEKDAYS VARCHAR(300) NOT NULL,
DEPARTURE_AIRPORT_CODE VARCHAR(100),
SCHEDULED_DEPARTURE_TIME TIMESTAMP NOT NULL,
ARRIVAL_AIRPORT_CODE VARCHAR(100),
SCHEDULED_ARRIVAL_TIME TIMESTAMP NOT NULL,


CONSTRAINT FLIGHT_PK 
PRIMARY KEY (FLIGHT_NUMBER),



CONSTRAINT FLIGHT_FK
FOREIGN KEY(DEPARTURE_AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE)
ON DELETE CASCADE ON UPDATE CASCADE

CONSTRAINT FLIGHT_FK1
FOREIGN KEY(ARRIVAL_AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE)
ON DELETE CASCADE ON UPDATE CASCADE

)



-- not required
CREATE TABLE FLIGHT_LEG(
FLIGHT_NUMBER VARCHAR(300) ,
LEG_NUMBER VARCHAR(300),
DEPARTURE_AIRPORT_CODE VARCHAR(100),
SCHEDULED_DEPARTURE_TIME TIMESTAMP NOT NULL,
ARRIVAL_AIRPORT_CODE VARCHAR(100),
SCHEDULED_ARRIVAL_TIME TIMESTAMP NOT NULL,

CONSTRAINT FLIGHT_LEG_PK
PRIMARY KEY(FLIGHT_NUMBER,LEG_NUMBER),

CONSTRAINT FLIGHT_LEG_FK1
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER)
ON DELETE CASCADE ON UPDATE CASCADE,

CONSTRAINT FLIGHT_LEG_FK2
FOREIGN KEY(DEPARTURE_AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE)
ON DELETE CASCADE ON UPDATE CASCADE,

CONSTRAINT FLIGHT_LEG_FK3
FOREIGN KEY(ARRIVAL_AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE)
ON DELETE CASCADE ON UPDATE CASCADE


)






CREATE TABLE FLIGHT_INSTANCE(
FLIGHT_NUMBER VARCHAR(300) ,
FLIGHT_DATE DATE,
NUMBER_OF_AVAILABLE_SEATS INTEGER,
AIRPLANE_ID VARCHAR(200),
DEPARTURE_TIME TIMESTAMP NOT NULL,
ARRIVAL_TIME TIMESTAMP NOT NULL,

CONSTRAINT FLIGHT_INSTANCE_PK
PRIMARY KEY(FLIGHT_NUMBER,FLIGHT_DATE),

CONSTRAINT FLIGHT_INSTANCE_FK1
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER)
ON DELETE CASCADE ON UPDATE CASCADE,



CONSTRAINT FLIGHT_INSTANCE_FK2
FOREIGN KEY(AIRPLANE_ID) REFERENCES AIRPLANE(AIRPLANE_ID)
ON DELETE CASCADE ON UPDATE CASCADE


)




CREATE TABLE FARE(
FLIGHT_NUMBER VARCHAR(300),
FARE_CODE VARCHAR(20),
AMOUNT DOUBLE,
RESTRICTIONS VARCHAR(20),

CONSTRAINT FARE_PK
PRIMARY KEY(FLIGHT_NUMBER,FARE_CODE,RESTRICTIONS),


CONSTRAINT FARE_FK
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER)
ON DELETE CASCADE ON UPDATE CASCADE

)

CREATE TABLE AIRPLANE_TYPE(
AIRPLANE_TYPE_NAME VARCHAR(200),
MAX_SEATS INTEGER,
COMPANY VARCHAR(200),

CONSTRAINT AIRPLANE_TYPE_PK
PRIMARY KEY(AIRPLANE_TYPE_NAME)
)




CREATE TABLE CAN_LAND(
AIRPLANE_TYPE_NAME VARCHAR(200),
AIRPORT_CODE VARCHAR(100),

CONSTRAINT CAN_LAND_PK
PRIMARY KEY(AIRPLANE_TYPE_NAME,AIRPORT_CODE),

CONSTRAINT CAN_LAND_FK1
FOREIGN KEY(AIRPLANE_TYPE_NAME) REFERENCES AIRPLANE_TYPE(AIRPLANE_TYPE_NAME)
ON DELETE CASCADE ON UPDATE CASCADE,

CONSTRAINT CAN_LAND_FK2
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE)
ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE AIRPLANE(
AIRPLANE_ID VARCHAR(200),
TOTAL_NUM_OF_SEATS INTEGER,
AIRPLANE_TYPE_NAME VARCHAR(200),

CONSTRAINT AIRPLANE_PK
PRIMARY KEY(AIRPLANE_ID),

CONSTRAINT AIRPLANE_FK
FOREIGN KEY(AIRPLANE_TYPE_NAME) REFERENCES AIRPLANE_TYPE(AIRPLANE_TYPE_NAME)
ON DELETE CASCADE ON UPDATE CASCADE

)



CREATE TABLE SEAT_RESERVATION(
FLIGHT_NUMBER VARCHAR(300) ,
FLIGHT_DATE DATE,
SEAT_NUMBER VARCHAR(6),
CUSTOMER_NAME VARCHAR(200),
CUSTOMER_PHONE VARCHAR(20),

CONSTRAINT SEAT_RESERVATION_PK
PRIMARY KEY(FLIGHT_NUMBER,FLIGHT_DATE,SEAT_NUMBER),

CONSTRAINT SEAT_RESERVATION_FK1
FOREIGN KEY(FLIGHT_NUMBER,FLIGHT_DATE) REFERENCES FLIGHT_INSTANCE(FLIGHT_NUMBER,FLIGHT_DATE)
ON DELETE CASCADE ON UPDATE CASCADE


)






















